version: '3'
services:
    web:
        image: jakubboucek/lamp-devstack-php:debug
        depends_on:
            - mysqldb
        environment:
            APP_DEBUG: 1
            XDEBUG_CONFIG: "client_host=host.docker.internal"
        ports:
            - "127.0.0.1:8080:80"
        restart: always
        volumes:
            - ".:/var/www/html"

    mysqldb:
        image: jakubboucek/lamp-devstack-mysql
        environment:
            MARIADB_DATABASE: default
            MARIADB_ROOT_PASSWORD: devstack
        ports:
            - "127.0.0.1:33060:3306"
        restart: always
        volumes:
            - "./docker/mysql/data:/var/lib/mysql"
